package com.lifeforce.payer.request.domain;

public enum StatusReason {
    // PENDING STATUS REASONS
    EVIDENCE_UPDATED,
    AWAITING_EVIDENCE,
    CRITERIA_NOT_MET,
    MANUAL_REVIEW_REQUIRED,
    PENDING_EVALUATION,

    // APPROVED STATUS REASONS
    AUTO_APPROVED,
    MANUAL_APPROVED,
    PRIOR_AUTH_NOT_REQUIRED,

    // REJECTED STATUS REASONS
    NOT_COVERED,
    COVERAGE_INACTIVE,
    OUT_OF_NETWORK,
    SERVICE_EXCLUDED,
    MANUAL_REJECTED
}
